- server/server.py
Addressed a comment's concern about unnecessary use of if, elif, and else statements on server.py.
> Removed verbose code

- server/energy_scheduler.py
- server/kepler_model_trainer.py
- server/prometheus_datapipeline_functions.py
- server/server.py
- tests/kepler_regression_model_tests.py
First step was to revamp the model. Used Keras Functional API and used up to date code for preprocessing. The models used are still strictly a linear regression model, and they seem to be inaccurate (but this is because the datasets only have 5 rows and are completely made up). Second step included implementing the prometheus scraper. All that is needed is to include the configuration data for the tfio.experimental.IODataset.from_prometheus which should be in the configuration yaml on Kepler. A temporary scheduler was also provided which will commence scraping and training every day at 12 am. This can be replaced with a cron job if necessary. A major todo would be to implement a function which will check the loss after training and only save the model if the loss is in an acceptable …
> Kepler model

- server/kepler_model_trainer.py
Included Correlation Coefficient for testing.
> Correlation Coefficient Included

- server/model_server.py
This PR adds the following API.
```
/best-models
GET
```
Parameters
|key|value|description
|---|---|---|
|fg (optional)|[FeatureGroup](https://github.com/sustainable-computing-io/kepler-model-server/blob/a13ec978d4e73fa168d7ba3cad7b9cdff2477a50/server/train/train_types.py#L29)|query feature group
|ot (optional)|[ModelOutputType](https://github.com/sustainable-computing-io/kepler-model-server/blob/a13ec978d4e73fa168d7ba3cad7b9cdff2477a50/server/train/train_types.py#L38)|query output_type
|filter (optional)|string|query filter expression
example:
```bash
curl localhost:8100/best-models
``` 
```json
{"AbsComponentModelWeight": {"Full": "KerasCompWeightFullPipeline"}, 
"AbsComponentPower": {"Full": "KerasCompFullPipeline"}, "AbsModelWeight": {"CounterOnly": "Sample"}, 
"AbsPower": {"Full": …
```
> add api route for listing best available models

- demo/Dockerfile
- demo/Makefile
- demo/README.md
- demo/demo.py
- demo/deployment.yaml
This PR includes additional template for building docker image and deployment manifest. 
> Add guide for build/deploy demo

- .github/workflows/docker-base-image.yml
- server/dockerfiles/requirements.txt
This PR adds a workflow to rebuild and push base image if requirements.txt or Dockerfile.base are changed.
> Rebuild base image if needed

- manifests/dev/deployment.yaml
- manifests/host-local/deployment.yaml
- manifests/local/deployment.yaml
- server/train/pipe_util.py
Namespace should now be set to kepler. The Kepler Operator Model Server Controller namespace will also be set to kepler.
> Updated Namespace

- server/train/pipeline.py
- server/util/loader.py
This PR fixed wrong model_url path from typo.
> fix weight-type url path

- README.md
- contributing.md
- doc/model_feature.md
- doc/model_format.md
- doc/model_output.md
- doc/train_pipeline.md
This PR added the information about model format for future contribution corresponding to the issue https://github.com/sustainable-computing-io/kepler-model-server/issues/63.
> update model format description

- manifests/dev/xgboost_deploy.yaml
Include kubernetes deployment configuration to test the XGBoost Pipeline.
> Include XGBoost Pipeline exposure

- src/train/online_trainer.py
> fix online-train bug

- cmd/README.md
- cmd/main.py
- src/train/extractor/extractor.py
- src/train/profiler/profiler.py
- src/util/prom_types.py
As proposed in https://github.com/sustainable-computing-io/kepler-model-server/issues/132, this PR add plot function to visualize data, estimation samples, and estimation error from entrypoint command.
After applying a new dataset that I found that we also need to handle the case that metrics are available only for some feature groups at some specific timestamp. 
This PR also include the fix for https://github.com/sustainable-computing-io/kepler-model-server/issues/133 by adding `container_id` column to the id. 
> add plot function in entrypoint and fix extractor bug

- cmd/README.md
- cmd/main.py
- src/train/extractor/extractor.py
- src/train/extractor/smooth_extractor.py
- src/train/pipeline.py
- src/train/trainer/XGBoostTrainer/main.py
- src/util/extract_types.py
- src/util/prom_types.py
- src/util/train_types.py
- tests/estimator_model_test.py
- tests/extractor_test.py
- tests/model_tester.py
- tests/xgboost_test.py
This PR is to add accelerator feature to model training.
Now kepler can collect accelletor metrics and report to Prometheus,  for example:
kepler_node_accelerator_intel_qat{instance="cpio-5",qatDevID="qat_dev0",source="intel-qat",type="latency"} 46750
kepler_node_accelerator_intel_qat{instance="cpio-5",qatDevID="qat_dev1",source="intel-qat",type="latency"} 0
And in this pr, hope to add accelerator feature(AcceleratorOnly) for querying data and training power models.
> Add accelerator feature

- .github/workflows/docker-base-image.yml
- cmd/README.md
- dockerfiles/requirements.txt
- model_training/script.sh
This PR fixes https://github.com/sustainable-computing-io/kepler-model-server/issues/143 and also correct command in the entrypoint README. 
> fix entrypoint bug and update README

- src/train/trainer/scikit.py
Fix the bug mentioned in https://github.com/sustainable-computing-io/kepler-model-server/issues/152 by covering the case of intercept in float format. 
> fix bug on get weight

- model_training/benchmark/stressng.yaml
This PR is to address #72 and #83.
> add more scenarios to stress-ng

- .github/workflows/docker-base-image.yml
This PR is to prepare the main repo for the next release (v0.7). 
The first step, we need to make the base image available. 
> update base image for 0.7

- cmd/cmd_util.py
- cmd/main.py
This PR adds an option `--to-csv` to export the query results in csv format when calling query command. 
The csv output will be in the `[output_name]_csv` folder.
Also, this PR updates some outdated description, especially with separation of `pipeline-name` and `abs-pipeline-name`. The former is used for train output while the latter is used for specifying trained pipeline that will be used for trainer isolator.
> add to-csv option to query command and correct outdated description

- .github/workflows/collect-train.yml
- .github/workflows/push-to-main.yml
- .github/workflows/train.yml
- cmd/README.md
cause of failure in https://github.com/sustainable-computing-io/kepler-model-server/actions/runs/7675767067
> fix wrong image name

- .github/workflows/pr.yml
IMO, it seems we just need a PR test and a Push test.
Once for PR check trigger and one for Push(as PR been merged to main).
hence adjust CI settings.
> [CI] adjust CI settings

- .github/workflows/push-to-main.yml
This reverts commit 887cc33c5e84212c2121c5bb9f5946577c9d42cf.
> ci: do not overwrite already published images

- .github/workflows/build-push.yml
- .github/workflows/integration-test.yml
- .github/workflows/tekton-test.yml
- Makefile
- dockerfiles/Dockerfile
- dockerfiles/Dockerfile.base
- dockerfiles/Dockerfile.test
- dockerfiles/Dockerfile.test-nobase
- manifests/base/patch/patch-estimator-sidecar.yaml
- manifests/offline-trainer/offline-trainer.yaml
- manifests/server/online-train/patch-trainer.yaml
- manifests/server/server.yaml
- manifests/test/file-server.yaml
- manifests/test/model-request-client.yaml
- manifests/test/power-request-client.yaml
- model_training/s3/Dockerfile
- model_training/tekton/pipelines/collect.yaml
- model_training/tekton/pipelines/complete-train.yaml
- model_training/tekton/pipelines/single-train.yaml
- model_training/tekton/tasks/extract-task.yaml
- model_training/tekton/tasks/isolate-task.yaml
- model_training/tekton/tasks/original-pipeline-task.yaml
- model_training/tekton/tasks/s3/aws-s3-load.yaml
- model_training/tekton/tasks/s3/aws-s3-push.yaml
- model_training/tekton/tasks/s3/ibmcloud-s3-load.yaml
- model_training/tekton/tasks/s3/ibmcloud-s3-push.yaml
- model_training/tekton/tasks/train-task.yaml
- pyproject.toml
- src/server/model_server.py
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
(cherry picked from commit 49412516dee5eb62bb47eae7156e250065cbf31d)
> chore(python): upgrade to 3.10

- pyproject.toml
This combines all updates from dependabot to single pr - https://github.com/sustainable-computing-io/kepler-model-server/pulls/app%2Fdependabot 
Additionally the dependencies are sorted in alphabetical order
> chore(deps): update deps to match dependabot

- model_training/tekton/README.md
This commit mainly fixes the secret example snippet according to the cloud provider, and also fences the code blocks along with removing the necessary whitespaces
> fix(tekton): update the README

- .github/workflows/collect-train.yml
- .github/workflows/train.yml
- tests/e2e_test.sh
Add missing changes, following up the PR https://github.com/sustainable-computing-io/kepler-model-server/pull/283.
> change image version to latest

- cmd/main.py
- pyproject.toml
- src/train/extractor/extractor.py
- src/train/extractor/preprocess.py
- src/train/isolator/isolator.py
- src/util/loader.py
- tests/estimator_model_test.py
- tests/model_tester.py
Code changes required are mostly to address the exception raised when
computing mean of columns where some of the columns contained non
numeric data.
E.g. df.mean()[numeric_cols] is now changed to df[numeric_cols].mean()
---
This replaces all dependabot upgrades with a single update that resolves
conflict when upgrading individual package.
See: https://github.com/sustainable-computing-io/kepler-model-server/pulls/app%2Fdependabot
> chore(pyproject): upgrade dependencies

- src/util/loader.py
Follow up previous PR https://github.com/sustainable-computing-io/kepler-model-server/pull/325 after retrain and upload the model to db.
> change default pipeline to ec2-0.7.11

- model_training/README.md
- model_training/script.sh
This commit improves the script used to setup the cluster for model training.
Key changes:
- Improved the readability through proper formatting
- Fixed `cluster_up` failure due to incorrect `KUBECONFIG` setting
- Applied shellcheck for script linting
- Exported only necessary variables to avoid environment pollution
- Removed `kubectl` command installation as it is already a pre-requisite
- Updated to `v0.0.5` for local-dev-cluster and `latest` for model-server image
- Updated the README to reflect these changes
**Note: This doesn't change the existing definitions to keep the scope minimum**
> fix: enhance cluster setup script for model training

- .github/workflows/collect-data-self-hosted.yml
- .github/workflows/integration-test.yml
- .github/workflows/tekton-test.yml
- .github/workflows/train-model.yml
- model_training/script.sh
bump up kepler-action to 0.0.8
> bump up kepler-action to 0.0.8

- src/kepler_model/estimate/model_server_connector.py
- src/kepler_model/server/model_server.py
- src/kepler_model/util/loader.py
Address issue in comment https://github.com/sustainable-computing-io/kepler-model-server/pull/392
> address issue in comment #392, define ModelListParam

- .github/pull_request_template.md
This PR is motivated by @sthaha to mark a best practice to track unresolved issue in the PR.
> chore: add PR template for checklist before merge

- src/kepler_model/estimate/model_server_connector.py
- src/kepler_model/server/model_server.py
- tests/model_select_test.py
according to the request change in kepler PR https://github.com/sustainable-computing-io/kepler/pull/1684#discussion_r1730640450, this PR updates API param from spec to machine_spec.
---
```bash
hatch fmt
```
- must-fix: the logic seems wrong here. Could you please fix this?
- minor: reciever has a typo
- minor: code can be refactored to better readabilty
- nit: extra space, coma, ..  etc
> chore: change spec to machine_spec in server /model

- .github/pull_request_template.md
This commit improves the pull request template. It simplify the checklist items and improve the formatting. Also enhances descriptions of (`must-fix`,`minor`,`nit`)
---
```bash
hatch fmt
```
- must-fix: the logic seems wrong here. Could you please fix this?
- minor: reciever has a typo
- minor: code can be refactored to better readabilty
- nit: extra space, coma, ..  etc
> docs: improve the pull request template

- .github/workflows/commit-msg.yml
This commit adds a workflow to check the commit message making sure that all commit messages are following the [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
Addresses: #333
Sample CI run: https://github.com/sustainable-computing-io/kepler-model-server/actions/runs/10576193836/job/29301496265?pr=417
---
```bash
hatch fmt
```
- must-fix: the logic seems wrong here. Could you please fix this?
- minor: reciever has a typo
- minor: code can be refactored to better readabilty
- nit: extra space, coma, ..  etc
> feat(ci): Add workflow to check commit message

- .github/pull_request_template.md
- .github/workflows/lint.yml
- Makefile
- README.md
- contributing.md
- docs/developer/README.md
- model_training/README.md
- model_training/cmd_instruction.md
- model_training/cpe_script_instruction.md
- model_training/tekton/README.md
- pyproject.toml
- src/kepler_model/cmd/README.md
- tests/README.md
This commit introduces a new workflow for linting markdown files across the repository. Key changes include:
- Introduces a new GH workflow to automatically check for markdownlint errors on each PR.
- Adds a new `make lint` target to Makefile, which runs `pymarkdownlnt`
- Adds `pymardownlnt` as a dependency in `pyproject.toml`, ensuring availability for both local and CI runs.
- Resolves all existing Markdown linting issues within the repository.
Partially address: #336 
---
```bash
hatch fmt
```
> feat(ci): Add markdownlint workflow

- src/kepler_model/cmd/README.md
This commit updates the model-server image version to `v0.7.11-2`
---
```bash
hatch fmt
```
> chore(docs): update model-server version

- .github/workflows/integration-test.yml
- .github/workflows/tekton-test.yml
- pyproject.toml
- src/kepler_model/estimate/model/model.py
- src/kepler_model/util/train_types.py
Reverts sustainable-computing-io/kepler-model-server#441
Reverting this after CI started to fail.
> Revert "fix(xgboost): Remove xgboost dependency to reduce image sizes"

- .github/workflows/tekton-test.yml
Enable tekton tests and integration tests for every PR, not just when base image changes.
---
```bash
make fmt
```
> fix(workflow): enable tekton test and integration test on every PR

- .github/workflows/release.yml
- src/kepler_model/train/extractor/extractor.py
- src/kepler_model/train/profiler/node_type_index.py
- tests/estimator_model_request_test.py
This commit updates the credentials in the release workflow to use the correct secrets defined for the repository.
This also updates the extractor and profiler code to make linting and formatting CI pass
---
```bash
make fmt
```
> fix(ci): update the credentails in release workflow

- .github/workflows/lint.yml
- src/kepler_model/train/extractor/extractor.py
- tests/estimator_model_request_test.py
This commit removes the debugging print statements from the `extractor.py` file
---
```bash
make fmt
```
> chore: remove debugging print statements

- .github/dependabot.yml
> nit: update DepBot setting
