server/kepler_model_trainer.py
server/server.py
tests/kepler_regression_model_tests.py

Before adding the new flask route for retrieving model weights and before implementing the Prometheus based pipeline, I noticed some important code changes that can make development for future contributors easier. First change I made was adding some decoupling between the flask server and the module for training the models called kepler_model_trainer.py (code that deals with directly handling the models are now placed in the kepler_model_trainer and code that deals with handling requests are strictly in the flask server). Second change I made was ensuring the model_type (which is for accessing the different linear regression trained models) was universal. Currently, we just have two models: core energy consumption and dram energy consumpion. For example, in one module, the model_types …

Refractored and improved code

---

README.md
server/energy_scheduler.py
server/prometheus.yml
server/prometheus_datapipeline_functions.py

As requested by Parul, a dummy prometheus server was set up to test the from_prometheus scraper. The prometheus.yml file is provided which just has prometheus monitor itself. Warning from_prometheus does not appear to be working on my end. I still made the WIP PR so other developers can try testing from_prometheus for themselves to see if it's an issue on my end only or if the tfio.experimental.IODataset.from_prometheus is unreliable and a new alternative must be set up (like with elasticsearch or with more primitive ways of scraping prometheus metrics). To test, run './prometheus' with the new yml file and then run energy_scheduler.py by calling 'python energy_scheduler.py'.

Included WIP code using dummy prometheus.

---

doc/train_pipeline.md
server/train/__init__.py
server/train/kepler_model_trainer.py
server/train/keras_pipe.py
server/train/pipeline.py
server/train/train_types.py

This PR introduces a guideline and abstract pipeline class to build a train pipeline that is compatible to kepler-estimator and new exporting prometheus metrics.
Please check the [train_pipeline.md](https://github.com/sunya-ch/kepler-model-server/blob/train-1/doc/train_pipeline.md) for detail.
Notes: I reused the existing training function for defining a training pipeline example in [keras_pipe.py](https://github.com/sunya-ch/kepler-model-server/blob/train-1/server/train/keras_pipe.py). 

add train pipeline guideline for compatability to kepler-estimator 

---

server/util/config.py

This PR implements functions to handle two environment configurations.
1. configurable parameters
I think we should set model parameters from config map if we are using Kubernetes-based cluster.
A key benefit is that we can share a single point of configuration. For example, share prometheus server endpoint/port with the co-operated prometheus system. share model path with Kepler estimator container.
The `getConfig` will support both setting from configmap mount volume and environment variable.
2. shared paths
I think we can provide model via the shared file system such as NFS.
This will prepare model path (create if not exists) at specific mount point. This is also extensible to other path such as initial dataset.

functions to configurable parameters and shared paths

---

server/dockerfiles/requirements.txt
server/prom/query.py
server/prom/query_test.py

This PR refactors the prometheus query approach with the following implementations.
- Instead of manually specify the metric label key on every reference, this refactoring  use pandas from handling query data and use a single point of grouped feature definition in `train/train_types.py`.
- All queries and prometheus parameters are from the configuration.
- Prefix `node_`, `curr_` are removed from the label to share grouped feature definition between pod and node stat.
- Query multiple metrics at the same time because the different trainning pipelines may use different set of query. For example, dynamic power trainning pipeline use pod stat not node stat.
note: there is a dependent getConfig call from PR https://github.com/sustainable-computing-io/kepler-model-server/pull/37.
usage: …

refactor prom query

---

server/main.py
server/train/__init__.py
server/train/keras_pipe.py
server/train/keras_pipe_test.py
server/train/keras_pipe_util.py
server/train/pipeline.py
server/train/train_types.py

This PR updates example `keras_pipe.py` to use non-prefix features corresponding to new prometheus query approach in this PR https://github.com/sustainable-computing-io/kepler-model-server/pull/38.
Also, update configuration and model path preparation using `getConfig`, `getPath` function from this PR https://github.com/sustainable-computing-io/kepler-model-server/pull/37.
To use new refactored trainning pipeline, check `server/main.py`
```python
import os
import sys
import time
util_path = os.path.join(os.path.dirname(__file__), 'util')
train_path = os.path.join(os.path.dirname(__file__), 'train')
prom_path = os.path.join(os.path.dirname(__file__), 'prom')
sys.path.append(util_path)
sys.path.append(train_path)
sys.path.append(prom_path)
from prom.query import PrometheusClient, …
```

update train module corresponding to refactored prom query

---

README.md
contributing.md

This PR updates README.md with API endpoint descriptions.
It includes the description about each output model type and recommendation of use, template for available list of model training pipelines. 
The previous description is updated and moved to contributing page for developers.

add description of power model and api endpoint

---

.github/workflows/cluster_deploy.yml
.github/workflows/deploy_server.yml
.github/workflows/docker-image.yml
manifests/host-local/deployment.yaml
manifests/host-local/trainer-patch.yaml
manifests/local/deployment.yaml
manifests/local/trainer-patch.yaml
server/online_trainer.py
server/prom/query.py

This PR updates the deployment manifests grouping by the storage choice (currently covers only host-local and (pod)local).
In addition, the PR includes the following CI workflows.
- reusable cluster_deploy: deploy Kind Cluster with kepler-model-server (and prometheus if online-trainer is enabled)
- server_only_with_local: call cluster_deploy to deploy kepler-model-server without online_trainer patch with pod local
- server_only_with_host-local:  similar to server_only_with_local but with hostpath PV and corresponding PVC and MNT_PATH config
- with_online_trainer: with prometheus and with side-car online trainer
Signed-off-by: Sunyanan Choochotkaew [sunyanan.choochotkaew1@ibm.com](mailto:sunyanan.choochotkaew1@ibm.com)

update deployment manifests and workflows

---

.github/workflows/cluster_deploy.yml
.github/workflows/deploy_server.yml
manifests/host-local/deployment.yaml
manifests/local/deployment.yaml
server/train/pipeline.py
server/util/loader.py

This PR implements a function to initially download the offline trained model by URL set in the configmap as below.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: kepler-model-server-cfm
namespace: monitoring
data:
...
INITIAL_MODELS_LOC: https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models
INITIAL_MODEL_NAMES: |
AbsComponentModelWeight=KerasCompWeightFullPipeline
AbsComponentPower=KerasCompFullPipeline
DynComponentPower=ScikitMixed
```
Also, `load_initial_models` input in the workflows/cluster_deploy.yml is no need anymore.

add loading initial models by config

---

server/dockerfiles/requirements.txt

I believe that Dockerfile.base is missing scikit-learn dependency which was causing the container to fail when deploying. Thus, scikit-learn==1.1.2 dependency had to be included in the requirements.txt.

Include scikit learn in kepler-model-server-base

---

.github/workflows/unittest.yaml
src/server/model_server.py
src/util/loader.py
tests/model_server_test.py

This PR extended and updated the server-api to work with new pipeline models (https://github.com/sustainable-computing-io/kepler-model-server/issues/75).
Need to merge that PR first. 
Signed-off-by: Sunyanan Choochotkaew [sunyanan.choochotkaew1@ibm.com](mailto:sunyanan.choochotkaew1@ibm.com)

Update server api to use new pipeline model

---

manifests/dev/deployment.yaml
manifests/dev/trainer-patch.yaml
manifests/dev/xgboost_deploy.yaml
manifests/host-local/deployment.yaml
manifests/host-local/trainer-patch.yaml
manifests/local/deployment.yaml
manifests/local/trainer-patch.yaml
server/util/config.py
src/util/config.py

Related to path change on kepler exporter in PR https://github.com/sustainable-computing-io/kepler/pull/566, there is also a path change defined in the model server.
This PR made a path change in corresponding test manifests and the source code to read the config from the expecting path. 

change config path to match kepler exporter

---

manifests/base/patch/patch-estimator-sidecar.yaml
src/util/loader.py

This PR changes repo to the official kepler-model-db according to this merge https://github.com/sustainable-computing-io/kepler-model-db/pull/6.

change repo to official org

---

cmd/main.py
manifests/base/kustomization.yaml
src/estimate/archived_model.py
src/estimate/estimator.py
src/estimate/model/model.py
src/estimate/model_server_connector.py
src/server/model_server.py
src/train/extractor/extractor.py
src/util/config.py
src/util/loader.py
tests/estimator_model_request_test.py
tests/estimator_power_request_test.py
tests/weight_model_request_test.py

This PR additionally fixes multiple bugs due to integration test to Kepler.
- feature data is missing when there is no unit values such as in acpi platform energy
- energy source field is missing from estimator PowerRequest
- model path is set `rapl` to default which can be misleading.
- cmd train supported only single energy source
- initUrlKeyMap and estimatorKeyMap are not valid anymore. The model specification is now combination of output type and energy source. 

fix bugs estimator has no energy source

---

src/train/trainer/__init__.py
src/train/trainer/scikit.py
tests/extractor_test.py

This PR is to fix the wrong MAE calculation bug as mentioned in https://github.com/sustainable-computing-io/kepler-model-server/issues/120. 
In addition, it adds some minor fixes: remove unused time_filtrer import and add space to return call in extractor_test.py

fix mae calculation bug

---

cmd/README.md
cmd/main.py
src/train/__init__.py
src/train/extractor/smooth_extractor.py
tests/extractor_test.py

According to feature request issue in https://github.com/sustainable-computing-io/kepler-model-server/issues/122, this PR implements SmoothExtractor to smooth the data with specific window size on extraction. 
This is also available to test via the entrypoint `cmd/main.py` with `--extractor smooth`.
As this PR has a base on https://github.com/sustainable-computing-io/kepler-model-server/pull/121 fix, please merge the fix first.

add SmoothExtractor

---

cmd/main.py

fix estimate bug

---

.github/workflows/build-push.yml
Makefile
manifests/base/kustomization.yaml
manifests/server/kustomization.yaml

This PR is to fix the issue https://github.com/sustainable-computing-io/kepler/issues/888#issuecomment-1694990086.
I added latest tag to the GitHub workflow and, at the same time, set the default image replacement to the latest tag in both base and server kustomization file. 

add latest tag on workflow and set to default image replacement

---

cmd/main.py
src/train/profiler/generate_scaler.py
src/train/profiler/profiler.py
src/train/trainer/SGDRegressorTrainer/main.py
src/train/trainer/SVRRegressorTrainer/main.py
src/train/trainer/__init__.py
src/train/trainer/scikit.py
tests/common_plot.py

The current code normalizes the feature data using [MinMaxScaler](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/preprocessing/_data.py#L277) or [StandardScaler](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/preprocessing/_data.py#L657).
The main problem with `MinMaxScaler` and `StandardScaler` is because they apply data [standardization](https://towardsdatascience.com/normalization-vs-standardization-quantitative-analysis-a91e8a79cebf) instead of simple normalization. In practices, standardization divides each feature by the standard deviation after the mean/min has been subtracted. The problem of subtracting values is because the resulted value could be negative, which will not make sense.
For example, let's consider the case of the …

Update the feature normalization to use maxAbsScaler

---

README.md
tests/e2e_test.sh

This PR is to replace complicated API description with quick start point for deployment and test.
The API should be moved to gh-page as pushed by the PR https://github.com/sustainable-computing-io/kepler-doc/pull/98.

move API to gh-page and replace with deployment and test

---

README.md
model_training/README.md

No python version requirement is documented, however, [Flask requires python 3.8+](https://flask.palletsprojects.com/en/2.3.x/installation/#python-version). The following error occurs when executing `pip install -r ../dockerfiles/requirements.txt` as instructed [here](https://github.com/sustainable-computing-io/kepler-model-server/blob/10e074224bd13df872f6b2ad63fbb2dbc7a0740b/model_training/README.md?plain=1#L86) with a lower python version:
`Could not find a version that satisfies the requirement flask==2.1.2 (from -r dockerfiles/requirements.txt (line 1)) (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9, 0.10, 0.10.1, 0.11, 0.11.1, 0.12, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, …

add required python versions to READMEs

---

src/server/model_server.py
src/util/loader.py

This PR is to fix the issue https://github.com/sustainable-computing-io/kepler-model-server/issues/162.
The previous pipeline format expects `node_type` in the group name but the new design move `node_type` specification to be a part of `model_name`. As a result, I move the logic to check compatibility of node_type to inside the loop.

change node-type check logic

---

Makefile
cmd/main.py
manifests/base/openshift/estimate-only/kustomization.yaml
manifests/base/openshift/estimate-with-server/kustomization.yaml
manifests/base/openshift/scc.yaml
manifests/base/openshift/serve-only/kustomization.yaml
manifests/base/patch/patch-estimator-sidecar.yaml
manifests/base/patch/patch-openshift.yaml
manifests/offline-trainer/offline-trainer.yaml
manifests/server/online-train/patch-trainer.yaml
manifests/server/server.yaml
manifests/set.sh
src/estimate/estimator.py
src/estimate/model/model.py
src/estimate/model_server_connector.py
src/server/model_server.py
src/util/config.py
src/util/loader.py
tests/README.md
tests/estimator_model_request_test.py
tests/model_server_test.py
tests/weight_model_request_test.py

This PR is to fix the issue mentioned in https://github.com/sustainable-computing-io/kepler-model-server/issues/157.
Also, this PR add `make manifest` to validate manifest before run `make deploy`.
Example output: 
```
> OPTS="SERVER OPENSHIFT_DEPLOY" make manifest
SERVER OPENSHIFT_DEPLOY
WARNING: version difference between client (1.23) and server (1.25) exceeds the supported minor version skew of +/-1
Preparing manifests...
deploy model server
patch openshift deployment for exporter (serve-only)
patch openshift deployment for server
Done ./manifests/set.sh
...
> OPTS="ESTIMATOR OPENSHIFT_DEPLOY" make manifest
ESTIMATOR OPENSHIFT_DEPLOY
WARNING: version difference between client (1.23) and server (1.25) exceeds the supported minor version skew of +/-1
Preparing manifests...
add …
```

add missing cases of openshift deployment

---

.github/workflows/integration-test.yaml
tests/README.md
tests/e2e_test.sh

This PR is to fill the integration test to latest kepler image mentioned in https://github.com/sustainable-computing-io/kepler-model-server/issues/66.
scenario|test cases|deploy options|status
|---|---|---|---|
Kepler with estimator only|Estimator can load model from config|ESTIMATOR|&#x2714;
Kepler with model server only|Latest Kepler image can request weight model from model server|SERVER|&#x2714;
- Remove previous `Latest Kepler image can power from estimator` because Kepler already check that on init. So, it can be covered by `Latest Kepler image is connected to estimator` case.

add missing integration check (exclude online-trainer)

---

.github/ISSUE_TEMPLATE/document.yaml

Indentation was misaligned in the document issue template.
Should fix:

fixed off indentation

---

cmd/README.md
cmd/main.py
src/train/isolator/isolator.py
src/train/isolator/train_isolator.py
tests/isolator_test.py

The added feature by this PR is clarified in https://github.com/sustainable-computing-io/kepler-model-server/issues/150.
Captured output from running `python tests/isolator_test.py`. `target-hints` is set to `["coremark"]`.
```
Target containers: ['f9ad0189dc595151bed60aecd626f9fe15b90855a4bbd2857ed61ed11e55de25/coremark-cpeh-2373875594-v6p99/coremark/default', '2728f549fb2a4257769546649faa778f533834089b65cac0a7f847ff24a1d685/coremark-cpeh-3084828579-n48ff/coremark/default', 'ab14b69a811565d1094b9485ebabf8d0bdae93d19530b603f7e472e21cd2adb6/coremark-cpeh-3101606198-gkszz/coremark/default', 'd6ff74f5dd9e6f0671e1f5449f1ecdbe1ffb859210e515ab3d623dc51d275e6a/coremark-cpeh-984120340-mj9t5/coremark/default', '023c357407ef4591283ed1dabd854df3e04cc566bbfb6d6bd8f0722d727276b0/coremark-cpeh-100089795 …
```

define hints as alternative to isolate container by names

---

src/estimate/estimator.py
tests/estimator_model_request_test.py

This PR is to fix the issue https://github.com/sustainable-computing-io/kepler-model-server/issues/170.
The energy source dimension is missing.
```
set NODE_TOTAL_ESTIMATOR to true.
set NODE_TOTAL_INIT_URL to https://raw.githubusercontent.com/sunya-ch/kepler-model-db/css-117/models/v0.6/css-117/core96_v0.6/acpi/AbsPower/BPFIRQ/GradientBoostingRegressorTrainer_1.zip.
set NODE_COMPONENTS_ESTIMATOR to true.
set NODE_COMPONENTS_INIT_URL to https://raw.githubusercontent.com/sunya-ch/kepler-model-db/css-117/models/v0.6/css-117/core96_v0.6/rapl/AbsPower/BPFIRQ/KNeighborsRegressorTrainer_1.zip.
clean socket
get archived model
get init url https://raw.githubusercontent.com/sunya-ch/kepler-model-db/css-117/models/v0.6/css-117/core96_v0.6/acpi/AbsPower/BPFIRQ/GradientBoostingRegressorTrainer_1.zip …
```

fix bug on same output type of power requests

---

dockerfiles/Dockerfile.base

Pull Request: Reduce Image Size and Vulnerability
Changes:
- Utilize `python3.8-slim` as the base image to reduce image size and vulnerability.
- Added `--no-cache-dir` flag during `requirements.txt` installation for further size reduction.
To-Do:
- Remove [`Dockerfiles/Dockerfile.base`](https://github.com/sustainable-computing-io/kepler-model-server/tree/main/dockerfiles) as it's no longer required.
- Delete [`.github/workflows/docker-base-image.yml`](https://github.com/sustainable-computing-io/kepler-model-server/tree/main/.github/workflows) as `python3.8-slim` is used as the base image in the Dockerfile.
This pull request enhances image efficiency and security. Please review and merge as appropriate.

Enhancement: Optimize Docker image size to reduce it below 1 GB (#154)

---

src/estimate/estimator.py

This PR is follow-up fix from the previous PR https://github.com/sustainable-computing-io/kepler-model-server/pull/171.
Adding dimension of output type causes a fatal error throw when estimator failed to get the model.

fill the case that failed to get output path

---

manifests/kepler/patch/patch-ci.yaml
src/train/exporter/writer.py

This PR add missing writer file.
This should fix the following error.
```
% ./script.sh quick_collect
benchmark.cpe.cogadvisor.io/sample created
Wait for 1 sample jobs to be completed, sleep 10s
Wait for sample to be completed... 0/1, sleep 10s
Wait for sample to be completed... 0/1, sleep 10s
Wait for sample to be completed... 0/1, sleep 10s
Benchmark job completed
Traceback (most recent call last):
File "cmd/main.py", line 29, in <module>
from train.exporter import exporter
File "/usr/local/cmd/../src/train/exporter/exporter.py", line 19, in <module>
from writer import generate_pipeline_page, generate_validation_results, append_version_readme
ModuleNotFoundError: No module named 'writer'
benchmark.cpe.cogadvisor.io "sample" deleted
```
Signed-off-by: Sunyanan Choochotkaew …

add missing writer file

---

README.md
model_training/README.md

Since we found some dependency issue from higher version (3.11), for now, we should specify the compatible version to 3.8 instead. 
_Note:_ 
Some could be fixed in the future by refactoring some implementation such as 
```bash
.../lib/python3.11/site-packages/pandas/core/nanops.py", line 720, in nanmean
the_sum = _ensure_numeric(the_sum)
```
Some could be fixed by adding some dependency:
```
../../scipy/meson.build:130:0: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and cmake
```
reference: https://github.com/ContinuumIO/anaconda-issues/issues/13157

change python version 3.8+ to 3.8

---

.github/workflows/build-push.yml
.github/workflows/docker-base-image.yml
Makefile
cmd/README.md
cmd/main.py
dockerfiles/Dockerfile
dockerfiles/Dockerfile.test
model_training/script.sh
src/util/loader.py

This PR must be merged after https://github.com/sustainable-computing-io/kepler-model-server/pull/182 because it depends on base image.

relabel with version 0.7

---

cmd/main.py
src/estimate/model/model.py
src/estimate/model/xgboost_model.py
src/train/trainer/XgboostFitTrainer/main.py
src/train/trainer/__init__.py
src/train/trainer/xgboost_interface.py
tests/trainer_test.py

This PR covers the issue about xgboost trainer integration in https://github.com/sustainable-computing-io/kepler-model-server/issues/89, https://github.com/sustainable-computing-io/kepler-model-server/issues/86.
Also, it is how we build the model for testing the local xgboost estimator on the kepler core: https://github.com/sustainable-computing-io/kepler/pull/1007.
However, to avoid contamination to v0.6, we need to merge the v0.7 relabel PR  https://github.com/sustainable-computing-io/kepler-model-server/pull/183 first. 

migrate xgboost to trainer implementation

---

.github/workflows/unittest.yaml
Makefile
dockerfiles/Dockerfile
dockerfiles/Dockerfile.test
dockerfiles/requirements.txt
manifests/set.sh

This PR is to fix previous failed CI. 
The integration test seems to be failed due to dependency of kubectl version. 
The unit test got an error due to new release of Werkzeug. Need to fix the version in base image.
```
Traceback (most recent call last):
File "src/server/model_server.py", line 1, in <module>
from flask import Flask, request, json, make_response, send_file
File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
from .app import Flask as Flask
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 27, in <module>
from . import cli
File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 17, in <module>
from .helpers import get_debug_flag
File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 14, in <module>
from …
```

fix unittest (fix dep)/integration test (remove short option)

---

src/estimate/model/model.py
src/train/trainer/__init__.py
src/train/trainer/scikit.py
src/train/trainer/xgboost_interface.py
src/util/train_types.py

This PR partially work on https://github.com/sustainable-computing-io/kepler-model-server/issues/174 and https://github.com/sustainable-computing-io/kepler/issues/943 by adding MAPE to metadata and add newly-introduced page cache hit to the bpf metric group.

add page_cache_hit and MAPE

---

cmd/main.py
src/train/exporter/exporter.py
src/train/exporter/writer.py
src/train/trainer/scikit.py
src/train/trainer/xgboost_interface.py
src/util/loader.py

This PR includes
- Encode xgboost as requested by https://github.com/sustainable-computing-io/kepler-model-server/pull/190#discussion_r1393200718
- Modify n_estimators parameter of XGBoost to reduce prediction overhead (previously, it was 10x to the other regressor)
- Fix inf MAPE when y_test contains zero.
- Reorganize exported folder
- Move preprocessed data, figure, and validation result to be under pipeline folder
- Add local xgboost section

encode xgboost weight, fix MAPE, reorganize exported folder

---

cmd/README.md
cmd/cmd_plot.py
cmd/cmd_util.py
cmd/main.py
src/train/trainer/__init__.py
src/train/trainer/scikit.py
src/train/trainer/xgboost_interface.py
src/util/extract_types.py

This PR is a prerequisite for leveraging Tekton pipeline (https://github.com/sustainable-computing-io/kepler-model-server/issues/194) including:
**significant changes:**
- refactor cmd (entrypoint) code by separating cmd_plot.py and cmd_util.py for sub functions
- add `data-path`, `abs-pipeline-name` parameters to specify any data path by argument and to separate pipeline for isolation and output pipeline, respectively
- add `isolate_from_data` and  `train_from_data` command to separate run isolator and trainer process out of the pipeline based on preprocessed dataframe.  `train_from_data` introduces a new parameter `trainers`.
- allow to create a new data folder if not exist for `query` command
- add missing `update_thirdparty_metrics` call in `train` command
- auto fill default_trainers …

add isolate_from_data and train_from_data, with refactor entrypoint (tekton prerequisite)

---

.github/workflows/unittest.yaml
Makefile
dockerfiles/Dockerfile.test-nobase
dockerfiles/requirements.txt

According to https://github.com/sustainable-computing-io/kepler-model-server/issues/187, this PR made the version upgrade of xgboost and update unit test workflow to build test image without base image if there is a change on base image related files (such as requirement.txt).

upgrade xgboost to 2.0.1

---

.github/workflows/integration-test.yml
.github/workflows/push-pr.yml
.github/workflows/tekton-test.yml
model_training/tekton/examples/complete-pipelinerun.yaml
model_training/tekton/examples/single-train/abs-power.yaml
model_training/tekton/examples/single-train/aws-push.yaml
model_training/tekton/examples/single-train/dyn-power.yaml
model_training/tekton/examples/single-train/ibmcloud-push.yaml
model_training/tekton/examples/test-collect.yaml
src/train/pipeline.py

Previously merged PR got error on retrain data from AWS COS. 
First error comes from too early collected data on COS. After recollecting and uploading to the COS, the first error is fixed and then I found another error comes in the code (pipeline.py). 
This PR fixes the error and update CI flow as follows:
- remove unnecessary docker login in integration test and tekton test
- add always condition to integration test and tekton test and check whether docker_secret is available instead. integration test and tekton test will run only when (1) no base change or (2) base change and has secret to build-push base. 
- add idle time to 100s to make sure that it has enough to create idle profile.

fix pipeline bug and workflow

---

cmd/cmd_plot.py
cmd/cmd_util.py
cmd/main.py
model_training/s3/s3-loader.py
src/train/exporter/exporter.py
src/train/exporter/validator.py
src/train/exporter/writer.py
src/train/pipeline.py
src/train/profiler/node_type_index.py
src/train/trainer/__init__.py

This PR includes two updates.
- Add metadata plot on export as below:
- Fix bugs:
- training pipeline stops when one of node_type is failed to be trained (some curvefit cannot find a fit curve on some specific data). --> fixed by adding try-catch on metadata save
- number of chips is miscalculated. --> changed to chips = int(cores/psutil.cpu_count(logical=False))
- increase trainer threads to be equal to the number of trainer
- top_key_path on s3 not initialized. 

Add metadata plot and Fix bugs

---

.github/workflows/push-pr.yml
dockerfiles/requirements.txt
src/train/profiler/node_type_index.py
src/train/trainer/ExponentialRegressionTrainer/main.py
src/train/trainer/LogarithmicRegressionTrainer/main.py
src/train/trainer/LogisticRegressionTrainer/main.py
src/train/trainer/curvefit.py

This PR includes the following improvement.
curvefit function:
- improve log fitting function by adding coefficient and bias value to avoid log(0) instead of if condition
- update log p0 function
- add p0 function for exponential for faster convergence
- increase maxfev for better fitting (especially for logistic function which is the most complex)
generate_spec:
- add vendor extraction (available only on BM so not include in the main specification yet)
- reformat processor with lower function
- correct chips number calculation and add threads_per_core
- for VM, max frequency is zero, use current instead
The updated results can be found [here](https://github.com/sunya-ch/kepler-model-db/tree/specpower/models/v0.7/specpower).
Before:
After:
Significant improvement can be observed for …

update curvefit (log func) and generate_spec 

---

.github/workflows/integration-test.yml
.github/workflows/push-pr.yml
.github/workflows/push-to-main.yml
manifests/kepler/patch/patch-ci.yaml
model_training/deployment/kepler.yaml

According to the action error https://github.com/sustainable-computing-io/kepler-model-server/actions/runs/8050258211/job/22588827198, it seems model server is failed to collect the energy data with latest kepler image.
```
==== bpf ====
1 pods: 	Valid
Valid data points:
>0
scenarioID    
20
intel_rapl data: 	[0]
acpi data: 	[0]
pod/test-collect-presteps-pod
Empty
==== bpf ====
1 pods: 	No data for ['']
1 pods: 	Zero data for ['']
0 pods: 	Valid
Valid data points:
Empty
intel_rapl data: 	[0]
acpi data: 	[0]
```
To freeze the supported version, this PR specifies a specific Kepler release version that should support (v0.7.7). 

specify kepler tag

---

.github/workflows/push-to-main.yml

This PR is to fix issue from previous PR. It seems that we cannot refer to env in the inputs. 
I changed the input to use outputs from check-branch step (same as push-pr CI) and confirmed the functionality locally.
https://github.com/sunya-ch/kepler-model-server/actions/runs/8281793909

fix env error in push-to-main ci

---

.github/workflows/integration-test.yml
manifests/base/patch/patch-estimator-sidecar.yaml
manifests/base/patch/patch-server-only.yaml
manifests/base/serve-only/kustomization.yaml
src/estimate/estimator.py
tests/e2e_test.sh

The current logic to obtain a new power model when getting a request and the requesting trainer is different from the current cache of power model is wrong.
It should set to False by default and set to True only when the current trainer is not equal to the requesting trainer name.

fix logic to obtain new model

---

manifests/kepler/kustomization.yaml
model_training/cpe_script_instruction.md
model_training/script.sh

As mentioned in https://github.com/sustainable-computing-io/kepler-model-server/pull/252#issuecomment-2065632597, the config path on Kepler repository has been changed. This PR updates the path. 
In addition, this PR also change export function name to prevent issue as reported in https://github.com/sustainable-computing-io/kepler-model-server/issues/251.

change kepler config path and export func name

---

.github/workflows/integration-test.yml

Fix issue https://github.com/sustainable-computing-io/kepler-action/issues/118 by upgrading local_dev_cluster_version.
credit: @SamYuan1990 

update local_dev_cluster_version to v0.0.5

---

pyproject.toml
src/__about__.py
src/estimate/estimator.py
src/server/model_server.py

This commit adds a pyproject.toml for kepler-model-server based on guidelines for creating python packaging[1]. The build backend used is hatch since hatch helps manage a lot of packaging and enviroment related chores easily.
`hatch shell` or (`pip install .`) installs a `model-server`, and an estimator script. Minimal changes are made to the files to get the script running.
[1]: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

chore(project): add pyproject.toml

---

pyproject.toml

This fixes `pip install .` which installs `model-server` and `estimator` that 
also requires `util` and `train` to be installed as well.

chore(pyproject): fix pip install not installing all packages

---

Makefile
dockerfiles/Dockerfile
dockerfiles/Dockerfile.base
dockerfiles/Dockerfile.test
dockerfiles/Dockerfile.test-nobase
manifests/base/patch/patch-estimator-sidecar.yaml
manifests/offline-trainer/offline-trainer.yaml
manifests/server/online-train/patch-trainer.yaml
manifests/server/server.yaml
manifests/test/file-server.yaml
manifests/test/model-request-client.yaml
manifests/test/power-request-client.yaml
model_training/s3/Dockerfile
model_training/tekton/pipelines/collect.yaml
model_training/tekton/pipelines/complete-train.yaml
model_training/tekton/pipelines/single-train.yaml
model_training/tekton/tasks/extract-task.yaml
model_training/tekton/tasks/isolate-task.yaml
model_training/tekton/tasks/original-pipeline-task.yaml
model_training/tekton/tasks/s3/aws-s3-load.yaml
model_training/tekton/tasks/s3/aws-s3-push.yaml
model_training/tekton/tasks/s3/ibmcloud-s3-load.yaml
model_training/tekton/tasks/s3/ibmcloud-s3-push.yaml
model_training/tekton/tasks/train-task.yaml
pyproject.toml
src/server/model_server.py

NOTE: - https://devguide.python.org/versions/ - 3.8 will soon be EOL
This buys us some more time upgrading to 3.11 or 3.12 which fails (`hatch shell`) at the moment and requires further investigation.

chore(python): upgrade to 3.10

---

.github/workflows/push-to-main.yml
Makefile
dockerfiles/Dockerfile
dockerfiles/Dockerfile.base
dockerfiles/Dockerfile.test
dockerfiles/Dockerfile.test-nobase
manifests/base/patch/patch-estimator-sidecar.yaml
manifests/offline-trainer/offline-trainer.yaml
manifests/server/online-train/patch-trainer.yaml
manifests/server/server.yaml
manifests/test/file-server.yaml
manifests/test/model-request-client.yaml
manifests/test/power-request-client.yaml
model_training/s3/Dockerfile
model_training/tekton/pipelines/collect.yaml
model_training/tekton/pipelines/complete-train.yaml
model_training/tekton/pipelines/single-train.yaml
model_training/tekton/tasks/extract-task.yaml
model_training/tekton/tasks/isolate-task.yaml
model_training/tekton/tasks/original-pipeline-task.yaml
model_training/tekton/tasks/s3/aws-s3-load.yaml
model_training/tekton/tasks/s3/aws-s3-push.yaml
model_training/tekton/tasks/s3/ibmcloud-s3-load.yaml
model_training/tekton/tasks/s3/ibmcloud-s3-push.yaml
model_training/tekton/tasks/train-task.yaml
pyproject.toml
src/server/model_server.py

Fixes 
```
❯ docker run --rm=true -it quay.io/sustainable_computing_io/kepler_model_server:v0.7.7
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "python3.10
": executable file not found in $PATH: unknown.
```
This caused by 0.7.7 image being overwritten by the CI post merge job

Revert python 3.10

---

.github/workflows/build-push.yml
.github/workflows/pr.yml
Makefile
dockerfiles/Dockerfile.base

This PR builds (but not push) base image if a change is detected in critical files.
This should help detect issues such as https://github.com/sustainable-computing-io/kepler-model-server/actions/runs/9834078233 where the build-and-push base failed after the PR was merged.

ci: build base image if a change is detected

---

cmd/main.py
src/train/ec2_pipeline.py
src/train/exporter/exporter.py
tests/e2e_test.sh

To provide more visualization of collected data on EC2, I add lines to save kepler_query_json and machine spec to the local path for later feature plot. 
In addition, this PR also contains minor fix (duplicated workload_content assignment) and remove overwriting of NodeAttribute.PROCESSOR to keep information of processor model instead of replacing with instance profile name.

enrich ec2 train/plot and remove replacement of NodeAttribute.PROCESSOR with instance profile

---

model_training/README.md
model_training/cmd_instruction.md

This PR adds instruction for guiding how to collect, train, and export power models manually with entrypoint (cmd/main.py).

add manual training with entrypoint instruction

---

cmd/cmd_plot.py
cmd/cmd_util.py
cmd/main.py
src/train/ec2_pipeline.py
src/train/profiler/node_type_index.py
tests/pipeline_test.py

This PR updates instance list according to latest list for 0.7.11 collected by [kepler-model-training-playbook](https://github.com/sustainable-computing-io/kepler-model-training-playbook). 
Additionally, fix some bugs (pipeline not defined if args.id not defined, attribute name on initialization).

update instance list and pipeline for ec2-0.7.11

---

cmd/cmd_util.py
model_training/cmd_instruction.md

To avoid misunderstanding from validate function, I make the function to filter the pods by inputting benchmark name to be optional with recommendation in the README file. 
Result with filter:
```
===========================================
Use benchmark name to filter pod results:
stressng
count   >0
scenarioID          query
kepler_container_bpf_block_irq_total         527    0
kepler_container_bpf_cpu_time_ms_total       527  260
kepler_container_bpf_net_rx_irq_total        527  121
kepler_container_bpf_net_tx_irq_total        527   58
kepler_container_bpf_page_cache_hit_total    527    0
```
Result without filter:
```
============================================
Present results from all pods:
count    >0
scenarioID          query
kepler_container_bpf_block_irq_total        4046     0 …
```

make filter pod by benchmark optional

---

src/train/exporter/writer.py

The power curve image is created after write call. So, it does not show in the README as expected for the first run.
This PR removes the condition to check file exists and just append. 

remove condition to append energy source

---

.github/workflows/train-model.yml

This PR is to fix the issue in retrain-model workflow: https://github.com/sustainable-computing-io/kepler-model-server/actions/runs/10137095697/job/28026878134.
The issue is that the ENERGY_SOURCE parameter is not used by train target and the default of [original train task](https://github.com/sustainable-computing-io/kepler-model-server/blob/main/model_training/tekton/tasks/original-pipeline-task.yaml) is `acpi,rapl-sysfs`. ec2 does not have acpi source so it throws an error.
Here is result of temporary workflow I tested locally in my repo: https://github.com/sunya-ch/kepler-model-server/actions/runs/10139182692

apply energy source param on train-model flow

---

pyproject.toml
src/train/specpower_pipeline.py
src/util/__init__.py
src/util/loader.py
src/util/train_types.py
tests/estimator_model_request_test.py
tests/minimal_trainer.py

This PR additionally add missing fixes and updates on bumping to v0.7.11 including removing cgroups feature group as raised in issue https://github.com/sustainable-computing-io/kepler-model-server/issues/262.

fix: add boto3, spec pipeline version, version export path, and BREAKING CHANGE remove group feature

---

src/util/extract_types.py
src/util/loader.py

fix 
```
FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
return pd.unique([col_to_unit_val(col) for col in power_columns if "package" in col])
```

fix: pd.unique warning and ignore file not found

---

src/train/specpower_pipeline.py
src/util/loader.py

As mentioned in https://github.com/sustainable-computing-io/kepler-model-server/issues/339, even if there is no metric name changes but there is incompatibility issue due to sklearn upgrade. This requires training a new pipeline and requires conversion of column names in specpower database. 

fix: incompatability of specpower model on 0.7.11

---

model_training/tekton/README.md

This commit replaces a non-existent URL for installing Tekton release 0.54.1 with the correct URL.
Fixes #369

doc(tekton): fix tekton release URL

---

.github/workflows/pr.yml
tests/e2e_test.sh

In addition to the target next release (currently 0.7.11-release), we should report the compatibility status to the latest version of Kepler.

chore: add integration test with latest

---

.github/workflows/unit-test.yml
.gitignore
Makefile
dockerfiles/Dockerfile.dockerignore
dockerfiles/Dockerfile.test-nobase.dockerignore
dockerfiles/Dockerfile.test.dockerignore
src/kepler_model/estimate/estimator.py
src/kepler_model/estimate/model_server_connector.py
src/kepler_model/server/model_server.py
src/kepler_model/train/profiler/node_type_index.py
src/kepler_model/util/loader.py
src/kepler_model/util/similarity.py
src/kepler_model/util/train_types.py
tests/README.md
tests/data/machine_spec/test
tests/model_select_test.py

Related to https://github.com/sustainable-computing-io/kepler-model-server/issues/216, this PR adds a logic to find a node_type from the spec information. 
The idea is:
1. find exact node_type that equals or covers the machine spec
2. if not found, compute similarity between the machine spec and each node_type and select the most similar node_type
3. if more than one candidates with the same score, find uncertainty of selection (frequency of selected type over all candidates) and select the most frequent one.
This PR also updates the machine spec discovery in estimator to align with the kepler PR https://github.com/sustainable-computing-io/kepler/pull/1684. The updated logic is to first check availability of mounted spec first. If not available, apply the discover function.
Signed-off-by: …

feat: update select logic with spec similarity computation

---

.github/workflows/integration-test.yml
Makefile
manifests/kepler/kustomization.yaml
manifests/kepler/patch/patch-ci.yaml

This fix the behavior that latest kepler image doesn't apply in integration CI.
integration test with fixed version
```yaml
Containers:
kepler-exporter:
Image:      quay.io/sustainable_computing_io/kepler:release-0.7.11
Port:       9102/TCP
Host Port:  0/TCP
Command:
/bin/sh
-c
Args:
/usr/bin/kepler -v=4 -redfish-cred-file-path=/etc/redfish/redfish.csv
```
integration test with latest version
```yaml
Containers:
kepler-exporter:
Image:      quay.io/sustainable_computing_io/kepler:latest
Port:       9102/TCP
Host Port:  0/TCP
Command:
/bin/sh
-c
Args:
/usr/bin/kepler -v=4 -redfish-cred-file-path=/etc/redfish/redfish.csv
```

fix: apply kepler tag to deploy manifests

---

manifests/base/patch/patch-estimator-sidecar.yaml
src/kepler_model/estimate/estimator.py
src/kepler_model/estimate/model_server_connector.py

This PR fixes the issue found by @sthaha that estimator calls model-request for multiple times. 
The root cause is that the estimator has the logic to check mismatch trainer. Kepler requests for the default trainer which is SGDTrainer but the estimator configmap set URL to GBR. For the case of estimator-only, it will never find the match one since it is statically set.
This PR adds a check whether the model-server is enabled or not before checking the mismatch.
To see the fix, check CI log for estimator-only case.

fix: mismatch model request check (unexpectedly-repeated model request)

---

src/kepler_model/util/config.py

This commit trims whitespaces including newlines when reading the MODEL_CONFIG file.

fix: ignore whitespaces in MODEL_CONFIG file

---

Makefile

```
hatch test -vvv -s ./tests/estimator_power_request_test.py"
^ run is missing here
```

fix: missing run in run-collector-client make target

---

Makefile

As mentioned in https://github.com/sustainable-computing-io/kepler-model-server/pull/370/files#r1719183945, this PR separate a commit to print log and try forcefully deleting the container in the case of deletion hang. 

chore: print log before stop container and try force remove

---

src/kepler_model/estimate/model_server_connector.py
src/kepler_model/server/model_server.py
tests/estimator_model_request_test.py
tests/weight_model_request_test.py

This PR adds variable `type` to the /best-models API so that it can list the model by filtering the node_type.
This is required by the new feature to select model based on node_type and spec.

feat: get type in /best-models API and pass source and type from estimator

---

manifests/compose/dev/compose.yaml

This useful during local development on a BM where we can run kepler without power meter.
Running this locally 
```
❯ dc logs estimator -f
estimator-1  | set NODE_TOTAL_ESTIMATOR to true.
estimator-1  | set NODE_TOTAL_INIT_URL to https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.7/specpower-0.7.11/acpi/AbsPower/BPFOnly/GradientBoostingRegressorTr
ainer_0.zip.
estimator-1  | set NODE_COMPONENTS_ESTIMATOR to true.
estimator-1  | INFO:kepler_model.estimate.estimator:clean socket
estimator-1  | set NODE_COMPONENTS_INIT_URL to https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.7/ec2-0.7.11/rapl-sysfs/AbsPower/BPFOnly/GradientBoostingRegres
sorTrainer_0.zip.
estimator-1  | INFO:kepler_model.estimate.estimator:started …
```

chore(compose): run kepler without power meters

---

Makefile
src/kepler_model/estimate/estimator.py
src/kepler_model/estimate/model_server_connector.py
src/kepler_model/train/profiler/node_type_index.py
src/kepler_model/util/config.py
src/kepler_model/util/loader.py
tests/data/machine/spec.json
tests/model_server_test.py

This PR updates kepler-model-server estimator with the same behavior as https://github.com/sustainable-computing-io/kepler/pull/1684.
1. pass --machine-spec file via command arguments
with spec file:
```
INFO:kepler_model.estimate.estimator:clean socket
INFO:kepler_model.estimate.estimator:initialize EstimatorServer with spec={'processor': 'intel_xeon_platinum_8259cl', 'cores': 96, 'chips': 2, 'memory': 377, 'frequency': 3500}
INFO:kepler_model.estimate.estimator:started serving on /tmp/estimator.sock
```
without spec file (auto-generated):
```
INFO:kepler_model.estimate.estimator:clean socket
INFO:kepler_model.estimate.estimator:initialize EstimatorServer with spec={'vendor': 'apple', 'processor': '', 'cores': 8, 'chips': 1, 'memory': 14, 'threads_per_core': 1} …
```

feat: add --machine-spec arg to estimator and get_machine_spec

---

Makefile
src/kepler_model/estimate/estimator.py
src/kepler_model/estimate/model/model.py
src/kepler_model/server/model_server.py
src/kepler_model/train/pipeline.py
src/kepler_model/train/profiler/node_type_index.py
src/kepler_model/train/trainer/__init__.py
tests/estimator_model_request_test.py
tests/model_server_test.py

replace https://github.com/sustainable-computing-io/kepler-model-server/pull/404.
This PR adds machine_spec to metadata on
(i) trainer - add machine_spec from pipeline node_type_index
(ii) model-server - update loaded model metadata if the machine_spec doesn't exist (old version pipeline)

feat: add machine_spec to metadata

---

model_training/tekton/pipelines/complete-retrain.yaml
model_training/tekton/pipelines/single-retrain.yaml

---
```bash
hatch fmt
```
---
fix the issue from previous merge #429 
Only either string and array is allowed for tekton params. Need to explicitly convert true (bool) to string.
https://github.com/sustainable-computing-io/kepler-model-server/actions/runs/10675504524/job/29587669626

fix: pass true as string in pipeline param

---

src/kepler_model/estimate/estimator.py
src/kepler_model/train/profiler/node_type_index.py
src/kepler_model/util/config.py
src/kepler_model/util/loader.py

This PR introduces the following changes
* improves logging to report file and line info `2024-09-12 05:49:15 ERROR loader.py:79: failed to load json metadata.json`
* removes unnecessary `cat ... |` when grepping for physical id in /proc/cpuinfo

fix(estimator): logging and machine-spec computation

---

.github/workflows/integration-test.yml
.github/workflows/tekton-test.yml
pyproject.toml
src/kepler_model/estimate/model/model.py
src/kepler_model/util/train_types.py

`xgboost` and its dependency `nvidia` each contribute to half the size of the model-server base image.
This commit:
- removes `xgboost`, and its dependency nvidia from the project
- changes to model training code which uses `xgboost` to detect if `xgboost` is not present and skips execution
Image size comparison:
- Image sizes before change
```
quay.io/sustainable_computing_io/kepler_model_server        v0.7.11-2        dce5c5495a67   18 minutes ago   1.21GB
quay.io/sustainable_computing_io/kepler_model_server_base   v0.7.11-2        c59e2a1a5f43   27 minutes ago   1.19GB
```
- Image sizes after change
```
quay.io/sustainable_computing_io/kepler_model_server        v0.7.11-2        1521f5b2612d   2 hours ago      688MB
quay.io/sustainable_computing_io/kepler_model_server_base   v0.7.11-2 …
```

fix(xgboost): Remove xgboost dependency to reduce image sizes

---

pyproject.toml
src/kepler_model/estimate/archived_model.py
src/kepler_model/estimate/estimator.py
src/kepler_model/util/config.py

Estimator improvements

---

pyproject.toml

This allows us to easily bring up jupyter lab by running
```
hatch run lab:note [--any optional args]
```

chore(pyproject): add an env to run jupyter lab

---

src/kepler_model/train/extractor/extractor.py
src/kepler_model/util/prom_types.py

This PR will enable process metrics to be used when training with vm metrics. Specifically, when vm metrics are enabled for training, models will be trained with features kepler_process from job="vm" and labels kepler_vm from baremetal.

feat(vm_metrics): Use process metrics when using vm metrics to train

---

manifests/compose/dev/grafana/dashboards/dev/dashboard.json

Allows selection of `kepler_**level**` and create panels for the following
---

chore(dashboard): compute mape, mse, mae for all levels

---

.github/workflows/integration-test.yml
.github/workflows/pr.yml
Makefile
hack/utils.bash
tests/README.md
tests/e2e_test.sh

This commit refactors the existing `e2e_test.sh` script, making it more
generic, modular.
Key updates include:
- Replaces the use of environment variables with command line arguments
for better clarity and flexiability.
```
💡 Examples:
e2e_test.sh --estimator
e2e_test.sh --server
e2e_test.sh --test
e2e_test.sh --db
e2e_test.sh --estimator --server
e2e_test.sh --estimator --server --db
```
- Test logs and other useful information are now stored in the `tmp/e2e` directory for better organization and accessibility.
- Adds a `utils.bash` file to store common utility functions
- Updates existing GH workflows to align with the refactored script and
adds a new step to upload test artifacts for easier debugging in case
of failures.
-  Updates the `README.md` file
Addresses #452 #469 
---
In …

chore: refactor and enhance e2e test script

---

src/kepler_model/estimate/estimator.py
src/kepler_model/server/model_server.py
src/kepler_model/train/exporter/validator.py
src/kepler_model/train/online_trainer.py
src/kepler_model/train/pipeline.py
src/kepler_model/train/profiler/profiler.py
src/kepler_model/train/trainer/__init__.py
src/kepler_model/util/__init__.py
src/kepler_model/util/config.py
src/kepler_model/util/loader.py
src/kepler_model/util/prom_types.py
src/kepler_model/util/saver.py

This modifies config to make use of proper python typing for config and to make use of predictable paths for directories
Changes include:
* adding new RESOURCE_DIR config for resources dir
* add typing info to get_config to return proper types
* fix casing to follow pep8
---
```bash
make fmt
```

fix(config): use predictable paths and proper typings

---

manifests/server/online-train/patch-trainer.yaml
manifests/server/openshift/online-train/patch-trainer.yaml
src/kepler_model/cmd/main.py
src/kepler_model/train/prom/prom_query.py
src/kepler_model/util/prom_types.py

This commit removes the following
* PROM_QUERY_START_TIME, PROM_QUERY_END_TIME since the config is only used in kepler_model main.py to be used as default values.
* PROM_HEADERS: since the current format is a `str` and the expected format for headers is `dict[str, str]` for header: value to be set in http requests. This is removed until get_config can handle parsing str -> dict[str, str]
---
```bash
make fmt
```

fix(prom): remove unused PROM_ configs

---

src/kepler_model/cmd/main.py

This commit updates the condition to check the length of `PROM_THIRDPARTY_METRICS` instead of comparing it to `[""]`
---
```bash
make fmt
```

fix: check length of PROM_THIRDPARTY_METRICS

---

.github/workflows/train-model.yml

[CI] nit fix for CI issue

---

dockerfiles/Dockerfile
dockerfiles/Dockerfile.test

This commit removes the `--platform` flag from `FROM` lines in the Dockerfiles as Docker discourages the use of hardcoded platform in the `FROM` instruction
Addresses #514 
---
```bash
make fmt
```

chore(Dockerfile): remove platform flag from FROM instruction

---

src/kepler_model/cmd/cmd_util.py
src/kepler_model/cmd/main.py
src/kepler_model/train/extractor/extractor.py

When training models with `kepler_vm_package_joules_total` or similar, we use the `trained_power_model` as energy source, this fixes the issue of getting the proper energy from prom metrics. 
Tested with the following command:
```bash
hatch run python cmd/main.py train --vm-train -e trained_power_model
```

chore: use kepler_vm metrics as energy source

---

model_training/cmd_instruction.md

This commit updates the commands to use the `kepler-model` package name instead of `python ...` to run the model training commands.
Addresses: #530
---
```bash
make fmt
```

chore(docs): update commands to use package name

---

model_training/README.md
model_training/script.sh
model_training/tekton/pipelines/collect.yaml
model_training/tekton/pipelines/complete-train.yaml
model_training/tekton/pipelines/single-train.yaml
model_training/tekton/tasks/extract-task.yaml
model_training/tekton/tasks/isolate-task.yaml
model_training/tekton/tasks/original-pipeline-task.yaml
model_training/tekton/tasks/train-task.yaml
src/kepler_model/train/ec2_pipeline.py

This commit removes the obsolete reference to `cmd/main.py`, aligning the codebase with the current state of the project.
---
```bash
make fmt
```

chore: remove the outdated reference of cmd/main.py

---

manifests/server/online-train/patch-trainer.yaml

Fix
```
> OPTS="ESTIMATOR SERVER ONLINE_TRAINER" make manifest
```
> Error: accumulating resources: accumulation err='accumulating resources from '../server': '/home/ninine/kepler-model-server/manifests/server' must resolve to a file': recursed accumulation of path '/home/ninine/kepler-model-server/manifests/server': no matches for Id ConfigMap.v1.[noGrp]/kepler-model-server-cfm.kepler; failed to find unique target for patch ConfigMap.v1.[noGrp]/kepler-model-server-cfm.kepler
---
```bash
make fmt
```
Signed-off-by: …

fix: unmatch namespace in online trainer patch
